### ISSUE TITLE
Error when running REST with the Emotiv playback data

### ISSUE THREAD

**Issue by sanpusil** [goodshawn12/REST#7]
Dear goodshawn12,

I'm having an error in Matlab when running REST with the emotiv data in the demo. I'm using Matlab 2014b. This is the error: 

*****
>> test_script
starting BCILAB...
running config script F:\REST-master\dependencies\BCILAB\bcilab_config.m...
running startup function...
Loading BCILAB dependencies...
Loading F:\REST-master\dependencies\BCILAB\dependencies\eeglab13_4_4b...
Warning: MATLAB has disabled some advanced graphics rendering features by switching to software OpenGL. For more information, click here. 
eeglab: options file is C:\Users\spusil\eeg_options.m
EEGLAB: adding "dipfit" v2.3 (see >> help eegplugin_dipfit)
EEGLAB: adding "firfilt" v1.6.1 (see >> help eegplugin_firfilt)
Loading F:\REST-master\dependencies\BCILAB\dependencies\cvx-1.21.b795...
Loading F:\REST-master\dependencies\BCILAB\dependencies\SIFT-private...
Initializing SIFT...
F:\REST-master\dependencies\BCILAB\dependencies\SIFT-private
SIFT: Adding subfolders.
Start SIFTing!

code is in F:\REST-master\dependencies\BCILAB\code
data is in F:\REST-master\dependencies\BCILAB\userdata
results are in F:\REST-master\dependencies\BCILAB\userdata
cache is disabled
temp is in F:\REST-master\dependencies\BCILAB-temp

 Welcome to the BCILAB toolbox on BRODMANN11!
 Launch time was: 22.3 seconds

pop_loadset(): loading file .\data\Demo_EmotivEPOC_EyeOpen.set ...
Warning: the name of the dataset has changed on disk, updating .dat & .fdt data file to the new name
Reading float file '.\data\Demo_EmotivEPOC_EyeOpen.fdt'...
Scaling components to RMS microvolt
Loading LSL library...
Creating data streaminfo...
Opening data outlet...
Preparing marker map...
Now playing back...
eeg_insertbound(): 1 boundary (break) events added.
eeg_checkset note: upper time limit (xmax) adjusted so (xmax-xmin)*srate+1 = number of frames
Scaling components to RMS microvolt
Scaling components to RMS microvolt
WARNING: The value assigned to srate in set_new is not in the typical range [0.1 100000], but was: 0
  using montage resources:/caps/Standard-10-5-Cap385.cap.
Using deprecated argument "flag_quantile/FlaggedQuantile" in function flt_clean_windows (help: Legacy parameter for pre-2012 methods. Quantile of data windows flagged for removal. Windows are emoved if flagged in all except for some possibly bad channels, controls the aggressiveness of the rejection.).
WARNING: The MVAR algorithm 'BSBL BO' depends on BSBL_BO.m, which cannot be located on the path. This algorithm will not be available.
WARNING: The MVAR algorithm 'BSBL L1' depends on BSBL_L1_noise.m, which cannot be located on the path. This algorithm will not be available.
WARNING: The MVAR algorithm 'T-MSBL' depends on TMSBL.m, which cannot be located on the path. This algorithm will not be available.
WARNING: The MVAR algorithm 'SCSA EM' depends on scsa_em.m, which cannot be located on the path. This algorithm will not be available.
Note: The head model named "resources:/headmodels/standard-Colin27-385ch.mat" was neither found in the base workspace nor could it be loaded as a file.
Using deprecated argument "num_bins/NumBins" in function make_func/@(f,a,frame__f3)feval(f,a{:}) (help: This parameter is now auto-determined).
Using deprecated argument "fit_quantiles/FitQuantiles" in function make_func/@(f,a,frame__f3)feval(f,a{:}) (help: Old Truncated Gaussian quantile. This was allowed to be a matrix holding an ensemble of alternative quantiles -- that is no longer needed/supported (instead the replacement parameter TruncateQuantile should be used).).
Using deprecated argument "min_badchans/MinAffectedChannels" in function flt_clean_windows (help: Legacy parameter for 2011 method. This is the minimum number of channels that need to be affected for the window to be considered "bad".).
Using deprecated argument "ignored_chans/MaxIgnoredChannels" in function flt_clean_windows (help: Legacy parameter for 2010 method. Maximum number or ratio of channels to ignore. These can contain arbitrary data without affecting the outcome (e.g., can be unplugged channels).).
Using deprecated argument "ref_wndlen/ReferenceWindowLength" in function flt_repair_bursts (help: Selection granularity for reference data. When clean data is extracted from the recording for calibrating the cutoff thresholds the data is chopped up into windows of this length. This parameters has been deprecated in favor of ReferenceExtraction.WindowLength.).
Using deprecated argument "ref_maxbadchannels/ReferenceMaxBadChannels" in function flt_repair_bursts (help: Maximum bad-channel fraction on reference data. The maximum fraction of bad channels per time window of the data that is used as clean reference EEG on which statistics are based. Instead of a number one may also directly pass in a data set that contains clean reference data (for example a minute of resting EEG). A lower values makes this criterion more aggressive. Reasonable range: 0.05 (very aggressive) to 0.3 (quite lax). This parameters has been deprecated in favor of ReferenceExtraction.MaxBadChannels.).
Using deprecated argument "ref_tolerances/ReferenceTolerances" in function flt_repair_bursts (help: Power tolerances on reference data. These are the power tolerances beyond which a channel in the clean reference data is considered "bad", in standard deviations relative to a robust EEG power distribution (lower and upper bound). This parameters has been deprecated in favor of ReferenceExtraction.PowerTolerances.).
Note: The operation 'pop_eegfilt' will neither allow to generate reliable predictions nor usable online models from the imported data set.
Note: The operation 'pop_runica' will neither allow to generate reliable predictions nor usable online models from the imported data set.

It is recommended that these operations be executed from BCILAB's processing palette, since the operations implemented there are online-capable.
io_loadset(): loading F:\REST-master\dependencies\BCILAB-temp\flushedsets\2527468776.sto...
Scanning potential marker channel 1 2 3 4 5 6 7 8 9 10 11 12 13 14 
Using deprecated argument "num_bins/NumBins" in function make_func/@(f,a,frame__f2)feval(f,a{:}) (help: This parameter is now auto-determined).
Using deprecated argument "fit_quantiles/FitQuantiles" in function make_func/@(f,a,frame__f2)feval(f,a{:}) (help: Old Truncated Gaussian quantile. This was allowed to be a matrix holding an ensemble of alternative quantiles -- that is no longer needed/supported (instead the replacement parameter TruncateQuantile should be used).).
Finding a clean section of the data...
Using deprecated argument "num_bins/NumBins" in function make_func/@(f,a,frame__f1)feval(f,a{:}) (help: This parameter is now auto-determined).
Using deprecated argument "fit_quantiles/FitQuantiles" in function make_func/@(f,a,frame__f1)feval(f,a{:}) (help: Old Truncated Gaussian quantile. This was allowed to be a matrix holding an ensemble of alternative quantiles -- that is no longer needed/supported (instead the replacement parameter TruncateQuantile should be used).).
Determining time window rejection thresholds...done.
Keeping 72.3% (43 seconds) of the data.
Estimating statistics...

Error using cell/ismember>cellismemberR2012a (line 192)
Input A of class cell and input B of class cell must be cell arrays of strings, unless one is a string.

Error in cell/ismember (line 56)
    [varargout{1:max(1,nargout)}] = cellismemberR2012a(A,B);

Error in REST>REST_OpeningFcn (line 232)
        rm_ind = ismember(handles.headModel.channelLabel, removed);

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in REST (line 71)
    gui_mainfcn(gui_State, varargin{:});

Error in test_script (line 104)
REST(opts)

********

Thank you in advance for your help!

San.

**Comment by goodshawn12** [comment]
Hi San,
Thanks for reporting the issue. Can you provide a bit more information? (1) Did you change any default setting / config (through a pop-up GUI) when you ran the test_script? (2) Can you set a break point in REST>REST_OpeningFcn (line 232) and see what are the content of "handles.headModel.channelLabel" and "removed"?
Best,
Shawn

**Comment by sanpusil** [comment]
Hi Shawn, 

Thanks for replying! So regarding your questions (1) I haven't change anything from the pop-up GUI or the script when it. (2) I set the break point and this is what I got: 

handles.headModel.channelLabel

ans = 

    'AF3'    'F7'    'F3'    'FC5'    'T7'    'P7'    'O1'    'O2'    'P8'    'T8'    'FC6'    'F4'    'F8'    'AF4'

K>> removed

removed = 

    []
    {1x1 cell}
    []
    []
And in that 1x1 cell there's nothing just " that. 

Best,

San.

**Comment by lucapton** [comment]
Hi San, 

Sorry for the delay. I just pushed a fix. Let me know if it works or not.

Luca

**Comment by sanpusil** [comment]
Hi,
It's working now. Thank you so much!
